# Generated by Django 5.1.1 on 2026-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
