# Generated by Django 5.1.1 on 2026-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_genre_movie_language_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
    ]
